### ISSUE TITLE
Iris gui crash on ROI click in single diffraction image window

### ISSUE THREAD

**Issue by furii** [LaurentRDC/iris-ued#9]
After loading a diffraction image from TIFF file and clicking the ROI button in the dialog displaying the image, the program crashes trying to access the "tVals" attribute (which a single diffraction image presumably does not have). 

--- COMMAND LINE OUTPUT ---
(base) C:\Users\krecinic>python -m iris
C:\userprograms\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning:
Conversion of the second argument of issubdtype from `float` to `np.floating` is
 deprecated. In future, it will be treated as `np.float64 == np.dtype(float).typ
e`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\userprograms\anaconda3\lib\site-packages\pyqtgraph\imageview\ImageVie
w.py", line 531, in roiClicked
    self.roiChanged()
  File "C:\userprograms\anaconda3\lib\site-packages\pyqtgraph\imageview\ImageVie
w.py", line 572, in roiChanged
    self.roiCurve.setData(y=data, x=self.tVals)
AttributeError: 'ImageView' object has no attribute 'tVals'

**Comment by LaurentRDC** [comment]
I could not replicate your issue. The built-in ROI button works as expected. Did you install PyQtGraph 0.10.0?

It could also be that the image that you tested has some unusual properties (TIFFs can have image series, for example). I'm attaching the image I used (in a ZIP files because TIFFs aren't supported by GitHub issues).
[tiff_test.zip](https://github.com/LaurentRDC/iris-ued/files/1946843/tiff_test.zip)

 Can you attach the image that crashed the GUI?

**Comment by furii** [comment]
Aha, it indeed works fine with the image that you sent me and crashes when I try with the following image:

[MCPIMG_20161201_180429.zip](https://github.com/LaurentRDC/iris-ued/files/1946901/MCPIMG_20161201_180429.zip)

This image was originally a PNG and was converted to TIF with IrfanView, maybe something went wrong there.

**Comment by LaurentRDC** [comment]
The image you attached reads to a 'color' image - one image per color channel. Otherwise it is a valid TIFF. I've committed a change that fixes the issue by using scikit-ued's [diffread ](http://scikit-ued.readthedocs.io/en/master/functions/skued.diffread.html#skued.diffread) function that handles this kind of problems.
